### ISSUE TITLE
Failed searching manifest (Mac OS X 10.8.5)

### ISSUE THREAD

**Issue by motw** [leafo/luarocks-site#6] opened 2014-03-07 17:48 UTC
I have the same problem as here @eltuerto https://github.com/leafo/moonrocks-site/issues/4.

```
luarocks install --server=http://rocks.moonscript.org moonrocks
Warning: Failed searching manifest: Failed loading manifest: Failed extracting manifest file

Error: No results matching query were found.
```

**Comment by kwiatowa26** [comment] 2015-01-06 16:42
In my case the problem was here:
...wget: unrecognized option '--no-check-certificate'..

My maverick's wget  had no ssl  compiled in and wget was selected as default downloader:

 --with-downloader)
      [ -n "$value" ] || die "Missing value in flag $key."
      case "$value" in
      wget|curl) LUAROCKS_DOWNLOADER="$value" ;;
      *) die "Invalid option: $value. See --help." ;;
      esac
      LUAROCKS_DOWNLOADER_SET=yes
      ;;
 
When I removed wget from OS everything started to work (with curl).

regards,

**Comment by hishamhm** [comment] 2015-01-08 18:56
@kwiatowa26 The configure script tries to use curl first. Is your installation calling `./configure --with-downloader=wget` explicitly?

**Comment by kwiatowa26** [comment] 2015-01-12 19:07
please ignore my citation from configure file - I introduced misconception.
The problem occured durring execution of torch7 installation script:
https://raw.githubusercontent.com/torch/ezinstall/master/install-luajit+torch 
It seems configure relays on default auto-dectection.
regards

**Comment by synchro--** [comment] 2015-01-15 02:01
@kwiatowa26  Indeed the issue is related to the Torch script. Is it fixed now? 

regards

**Comment by kwiatowa26** [comment] 2015-02-26 15:54
It seems that right now everything is OK!

**Comment by andrewwilson** [comment] 2015-06-22 20:41
I had the same issue with 2.2.0beta1. 
However I tracked it down to my ~/.cache/luarocks directory and everything in it being owned by root.
Changing the ownership (with "sudo chown -R myuser:mygroup ~/.cache/luarocks" or similar) fixed it for me.

**Comment by ramparte** [comment] 2015-07-12 22:04
FWIW, I had the same issue as kwiatowa26, there was an old copy of wget in /usr/local/bin for some reason. Just nuking it with brew link --overwrite wget fixed it.

**Comment by MrKonstantin** [comment] 2015-07-13 00:08
@andrewwilson, thanks!  "sudo chown -R myuser:mygroup ~/.cache/luarocks" fixed the same problem.

I think it would be great to mention about this option in docs: http://torch.ch/docs/getting-started.html#_

**Comment by leafo** [comment] 2015-08-14 06:03
closing out old issues

**Closed by leafo** 2015-08-14 06:03 UTC

**Comment by LinZichuan** [comment] 2016-03-13 15:37
@andrewwilson  I run ```sudo chown -R myuser:mygroup ~/.cache/luarocks``` and it starts cloning the iTorch, but stop because ```mkdir: cannot create directory ‘/home/linzichuan/torch/install/lib/luarocks/rocks/itorch/scm-1/bin’: Permission denied```
When I use ```sudo luarocks install itorch```, it will hold on there without any result. 
How should I do? Thanks very much !!!

**Comment by hishamhm** [comment] 2016-03-13 23:33
@LinZichuan fix permissions with chown in `/home/linzichuan/torch/install` as well.
